class TarotCard {
  final String id;
  final String nameTr;
  final String nameEn;
  final String emoji;
  final String meaning;
  final String reversedMeaning;
  final String element;

  const TarotCard({
    required this.id,
    required this.nameTr,
    required this.nameEn,
    required this.emoji,
    required this.meaning,
    required this.reversedMeaning,
    required this.element,
  });

  static const List<TarotCard> majorArcana = [
    TarotCard(
      id: '0',
      nameTr: 'Deli',
      nameEn: 'The Fool',
      emoji: '🃏',
      meaning: 'Yeni başlangıçlar, özgürlük, saf enerji, macera',
      reversedMeaning: 'Dikkatsizlik, risk, ihmal',
      element: 'Hava',
    ),
    TarotCard(
      id: '1',
      nameTr: 'Sihirbaz',
      nameEn: 'The Magician',
      emoji: '🎩',
      meaning: 'İrade gücü, beceri, yaratıcılık, manifestasyon',
      reversedMeaning: 'Manipülasyon, kötü niyet, yetersizlik',
      element: 'Ateş',
    ),
    TarotCard(
      id: '2',
      nameTr: 'Yüksek Rahibe',
      nameEn: 'The High Priestess',
      emoji: '🌙',
      meaning: 'Sezgi, gizem, iç bilgelik, bilinçaltı',
      reversedMeaning: 'Gizli ajanda, yüzeysellik, bilgisizlik',
      element: 'Su',
    ),
    TarotCard(
      id: '3',
      nameTr: 'İmparatoriçe',
      nameEn: 'The Empress',
      emoji: '👑',
      meaning: 'Bereket, annelik, güzellik, doğa, bolluk',
      reversedMeaning: 'Bağımlılık, aşırı koruyuculuk, kısırlık',
      element: 'Toprak',
    ),
    TarotCard(
      id: '4',
      nameTr: 'İmparator',
      nameEn: 'The Emperor',
      emoji: '⚔️',
      meaning: 'Otorite, yapı, güç, liderlik, istikrar',
      reversedMeaning: 'Tiranlık, sertlik, esneksizlik',
      element: 'Ateş',
    ),
    TarotCard(
      id: '5',
      nameTr: 'Aziz',
      nameEn: 'The Hierophant',
      emoji: '✝️',
      meaning: 'Gelenek, inanç, rehberlik, manevi bilgelik',
      reversedMeaning: 'Bağnazlık, kısıtlama, isyan',
      element: 'Toprak',
    ),
    TarotCard(
      id: '6',
      nameTr: 'Aşıklar',
      nameEn: 'The Lovers',
      emoji: '❤️',
      meaning: 'Aşk, uyum, ilişki, değerler, seçim',
      reversedMeaning: 'Uyumsuzluk, dengesizlik, kötü seçim',
      element: 'Hava',
    ),
    TarotCard(
      id: '7',
      nameTr: 'Savaş Arabası',
      nameEn: 'The Chariot',
      emoji: '🏆',
      meaning: 'Zafer, kararlılık, kontrol, başarı, özgüven',
      reversedMeaning: 'Agresiflik, kontrol kaybı, yenilgi',
      element: 'Su',
    ),
    TarotCard(
      id: '8',
      nameTr: 'Güç',
      nameEn: 'Strength',
      emoji: '🦁',
      meaning: 'Cesaret, sabır, içsel güç, şefkat',
      reversedMeaning: 'Zayıflık, şüphe, korkuya yenik düşme',
      element: 'Ateş',
    ),
    TarotCard(
      id: '9',
      nameTr: 'Münzevi',
      nameEn: 'The Hermit',
      emoji: '🕯️',
      meaning: 'İç yolculuk, yalnızlık, bilgelik, rehberlik',
      reversedMeaning: 'İzolasyon, yalnızlık, geri çekilme',
      element: 'Toprak',
    ),
    TarotCard(
      id: '10',
      nameTr: 'Kader Çarkı',
      nameEn: 'Wheel of Fortune',
      emoji: '🎡',
      meaning: 'Kader, döngüler, şans, dönüm noktası',
      reversedMeaning: 'Talihsizlik, kötü şans, dış baskı',
      element: 'Ateş',
    ),
    TarotCard(
      id: '11',
      nameTr: 'Adalet',
      nameEn: 'Justice',
      emoji: '⚖️',
      meaning: 'Denge, hakikat, neden-sonuç, sorumluluk',
      reversedMeaning: 'Adaletsizlik, dengesizlik, hesap vermeme',
      element: 'Hava',
    ),
    TarotCard(
      id: '12',
      nameTr: 'Asılan Adam',
      nameEn: 'The Hanged Man',
      emoji: '🔮',
      meaning: 'Bekleme, teslim olma, yeni bakış açısı, fedakarlık',
      reversedMeaning: 'Direniş, gecikme, boşa harcanan çaba',
      element: 'Su',
    ),
    TarotCard(
      id: '13',
      nameTr: 'Ölüm',
      nameEn: 'Death',
      emoji: '🌹',
      meaning: 'Dönüşüm, son ve başlangıç, değişim, yeniden doğuş',
      reversedMeaning: 'Değişime direnç, durgunluk, beklenmedik son',
      element: 'Su',
    ),
    TarotCard(
      id: '14',
      nameTr: 'Denge',
      nameEn: 'Temperance',
      emoji: '🌊',
      meaning: 'Sabır, denge, ılımlılık, iyileşme, harmoni',
      reversedMeaning: 'Aşırılık, dengesizlik, uyumsuzluk',
      element: 'Ateş',
    ),
    TarotCard(
      id: '15',
      nameTr: 'Şeytan',
      nameEn: 'The Devil',
      emoji: '🔥',
      meaning: 'Bağ, maddecilik, bağımlılık, gölge yönler',
      reversedMeaning: 'Özgürlük, bağları kırma, aydınlanma',
      element: 'Toprak',
    ),
    TarotCard(
      id: '16',
      nameTr: 'Kule',
      nameEn: 'The Tower',
      emoji: '⚡',
      meaning: 'Ani değişim, yıkım, açıklanma, kaos',
      reversedMeaning: 'Felaketten kaçınma, gecikmiş değişim',
      element: 'Ateş',
    ),
    TarotCard(
      id: '17',
      nameTr: 'Yıldız',
      nameEn: 'The Star',
      emoji: '⭐',
      meaning: 'Umut, iyimserlik, ilham, manevi rehberlik',
      reversedMeaning: 'Umutsuzluk, inanç kaybı, imansızlık',
      element: 'Hava',
    ),
    TarotCard(
      id: '18',
      nameTr: 'Ay',
      nameEn: 'The Moon',
      emoji: '🌕',
      meaning: 'Yanılsama, bilinçaltı, korku, sezgi, gizem',
      reversedMeaning: 'Kafa karışıklığı, korkuyu aşma, gerçeği görme',
      element: 'Su',
    ),
    TarotCard(
      id: '19',
      nameTr: 'Güneş',
      nameEn: 'The Sun',
      emoji: '☀️',
      meaning: 'Mutluluk, başarı, sevinç, canlılık, aydınlık',
      reversedMeaning: 'Geçici mutsuzluk, aşırı iyimserlik',
      element: 'Ateş',
    ),
    TarotCard(
      id: '20',
      nameTr: 'Yargı',
      nameEn: 'Judgement',
      emoji: '📯',
      meaning: 'Yeniden doğuş, içsel çağrı, hesap verme, özgürlük',
      reversedMeaning: 'Kendini yargılama, geçmişe takılma',
      element: 'Ateş',
    ),
    TarotCard(
      id: '21',
      nameTr: 'Dünya',
      nameEn: 'The World',
      emoji: '🌍',
      meaning: 'Tamamlanma, bütünleşme, başarı, tatmin',
      reversedMeaning: 'Tamamlanmamışlık, gecikme, eksik',
      element: 'Toprak',
    ),
  ];

  static List<TarotCard> getShuffled() {
    final cards = List<TarotCard>.from(majorArcana);
    cards.shuffle();
    return cards;
  }
}
